### ISSUE TITLE
Version 5 of the extension is not working on Ubuntu 20.04.1 LTS Wayland

### ISSUE THREAD

**Issue by drinim** [gonzaarcr/touchpad-window-switcher-gnome-ext#2]

**Comment by gonzaarcr** [comment]
Can confirm that the show desktop desnt’t work. You were talking about that or the switching? The switching works for me.

**Comment by drinim** [comment]
All the actions are not working in the new version.

**Comment by gonzaarcr** [comment]
I think is the `let` missing on `rounded_direction = 0`. Can you confirm? If not, maybe something on the .1 LTs upgrade but I doubt it.

**Comment by drinim** [comment]
That seems to be the issue, after adding the `let` before `rounded_direction = 0 ` everything works as expected.
