### ISSUE TITLE
Task switcher gets stuck

### ISSUE THREAD

**Issue by KristianUSN** [gonzaarcr/touchpad-window-switcher-gnome-ext#3]
So this technically works, swiping with three fingers bring up a task switcher and it does switch between the task. The issue is that the task switcher doesn't disappear after, and I can't interact with any applications because it pulls all input focus. Like trying to scroll in applications behind it just keeps scrolling through the tasks in the task switcher. I have to log out to make it go away. I'm running on Gnome version 3.38

**Comment by gonzaarcr** [comment]
I have yet to figure out a way of dealing with GNOME versions, I could do it with branches but then I wouldn’t be able to upload it to gnome extensions.

I think to solve this you only have to change `Clutter.Animation` to `Cluter.AnimationMode` [here](https://github.com/gonzaarcr/touchpad-window-switcher-gnome-ext/blob/master/touchpad_window_switcher%40gonza.com/mySwitcherPopup.js#L321).

Try it and tell me if it worked.

**Comment by KristianUSN** [comment]
That does indeed work :+1: Maybe it's not the right place to ask but what can I do to increase the sensitivity? I have to move my hand too much to go to the next task. I'd also love it to include open applications from other workspaces like the default gnome task switcher.

**Comment by gonzaarcr** [comment]
[Here](https://github.com/gonzaarcr/touchpad-window-switcher-gnome-ext/blob/master/touchpad_window_switcher%40gonza.com/extension.js#L16). `MOTION_THRESHOLD` is the sensitivity and `FIRST_MOTION_THRESHOLD` is used for the first one (is lower for more responsiveness).

For the workspace, it uses the same key so if should follow your settings. Make sure `gsettings get org.gnome.shell.window-switcher current-workspace-only` is false.

**Comment by gonzaarcr** [comment]
For the workspace think you have to change the [`GroupCyclerPopup._getWindows`](https://github.com/gonzaarcr/touchpad-window-switcher-gnome-ext/blob/master/touchpad_window_switcher%40gonza.com/myAltTab.js#L531) to:

```
	_init() {
		this._settings = new Gio.Settings({ schema_id: 'org.gnome.shell.app-switcher' });
		super._init();
	}

	_getWindows() {
		let app = Shell.WindowTracker.get_default().focus_app;
		let appWindows = app ? app.get_windows() : [];

		if (this._settings.get_boolean('current-workspace-only')) {
			const workspaceManager = global.workspace_manager;
			const workspace = workspaceManager.get_active_workspace();
			appWindows = appWindows.filter(
				window => window.located_on_workspace(workspace));
		}

		return appWindows;
	}
```

And add that `_init` above.
